### ISSUE TITLE
Does compile with minGW, but not MSVC

### ISSUE THREAD

**Issue by ep8472** [xioTechnologies/NGIMU-C-Cpp-Example#2]
Hi,
I was running the example code successfully (without Arduino, directly connected the NGIMU via USB to the computer, communicaion via serial). This works well when compiled with minGW64. However, I like to include the NGIMU into another project, which requires to be compiled with the MSVC2019 compiler. Doing so I get 372 errors... The very first error complains about `__packed__ ` (line 48: `typedef struct __attribute__((__packed__)) {`) in OscCommon.h, so I guess this is just some compiler directive issue, and the error cascade starts...

Is there a version of the osc99 header and cpp files for the MSVC compiler or alternatively, what do I need to do to compile with MSVC?

**Comment by xioTechnologies** [comment]
We have not attempted to compile OSC99 with MSVC so I cannot say precisely what is required to fix all of the errors.
